### ISSUE TITLE
Why no FromRawFd?

### ISSUE THREAD

**Issue by vi** [Rufflewind/tokio-file-unix#6]
Why there is no std::os::unix::io::FromRawFd impl?

How do I make tokio_file_unix::File from a fd number without workarounds like going though temporary socket/file/whatever struct?

**Comment by Rufflewind** [comment]
Currently you can do this via:

```rust
// either
tokio_file_unix::File::new_nb(std::fs::File::from_raw_fd(fd))
// or
tokio_file_unix::File::raw_new(std::fs::File::from_raw_fd(fd))
```

To implement `FromRawFd` for  `tokio_file_unix::File`, a choice would have to be made between these two, and I'm not sure which one makes a good default.

**Comment by vi** [comment]
Now I understand.

This (like "To implement `FromRawFd` (`from_raw_fd`), a choice would have to be made between `new_nb` and `raw_new` behaviour, and as there is no reasonable default this impl is not provided. Use `std::fs::File` as a proxy.") should probably be in the documentation, so searching for words "FromRawFd" and "from_raw_fd" finds something.

**Comment by Rufflewind** [comment]
Hm, actually…  `raw_new` is the only sensible choice for `impl FromRawFd for tokio_file_unix::File`, because `new_nb` returns `Result`.  Still, it's a risky one and I'd say it's better to encourage explicit use of `raw_new`.

Another complication comes from the choice of `F`: the ownership semantics of `tokio_file_unix::File<F>` are determined entirely by the underlying `F` object.  If you choose for example `F = std::fs::File`, you are implicitly asking for the file descriptor to be closed during destruction, which may or may not be intended behavior.

I'll add some explanation to the docs.
