### ISSUE TITLE
move to `tokio`

### ISSUE THREAD

**Issue by drahnr** [Rufflewind/tokio-file-unix#8]
Move to the new tokio crates setup

**Comment by Rufflewind** [comment]
Can you explain what you mean?  `tokio-file-unix` is a third-party supplement – it is not part of the official Tokio suite.

**Comment by drahnr** [comment]
Well, right now `tokio_core` is used which is going to be obsoleted by the `tokio` crate. I started to implementent those transition pieces, though I am not quite done yet.

**Comment by asonix** [comment]
The easy change that's needed is to migrate from [`PollEvented`](https://docs.rs/tokio-core/0.1.16/tokio_core/reactor/struct.PollEvented.html) to [`PollEvented2`](https://docs.rs/tokio/0.1.4/tokio/reactor/struct.PollEvented2.html)

This migration also drops the requirement for using `Handle`, since the event loop is now stored in the thread, and accessible without passing handles around.

It looks like tokio 0.1 drops the concept of Decoders and Encoders, so you'll likely need to implement Stream and Sink for your types.

All this said, I don't actually need these changes. My project [tokio-zmq](https://github.com/asonix/tokio-zmq) only cares about this crate's implementation of mio's `Evented`, so I'm already using it with tokio 0.1 and futures 0.2

**Comment by Rufflewind** [comment]
> Well, right now `tokio_core` is used which is going to be obsoleted by the `tokio` crate. I started to implementent those transition pieces, though I am not quite done yet.

Ah I see what you mean now.  I believe [libraries should continue to use the separate `tokio_*` crates](https://github.com/tokio-rs/tokio#project-layout), but `tokio_core` should be replaced by `tokio_reactor`.

> It looks like tokio 0.1 drops the concept of Decoders and Encoders, so you'll likely need to implement Stream and Sink for your types.

The `codec` submodule still exists in `tokio_io`, but for some reason is not exposed in `tokio`.

**Comment by Rufflewind** [comment]
Okay, so it seems there were a few more things that need to be changed than I had anticipated – not to mention migrating all the docs and examples to use the new Tokio.  Looks like `StdFile<Std*Lock<'a>>` won't really be usable in the new Tokio because futures must be `Send + 'static` to be `run`.  Instead I added some workaround functions for creating unbuffered standard `File`s.  You can try out the changes here:  https://github.com/Rufflewind/tokio-file-unix/tree/dev

(@drahnr Sorry for preempting your implementation!  There were quite a few major issues with this migration so I figured it would be simpler for me to do it directly.)

**Comment by drahnr** [comment]
@Rufflewind no worries, I hope to check it out some time next week

**Comment by Rufflewind** [comment]
Fixed by https://github.com/Rufflewind/tokio-file-unix/commit/342c9eadb21cd453304d5196dfa5a7f3e4e7f6ff .
